name: 'Deploy to Neocities'
description: 'Github Action to deplpoy a folder to Neocities.org'
branding:
  icon: cat
  color: yellow
inputs:
  apiToken:  # api token for site to deploy to
    description: 'Neocities API token for site to deploy to'
    required: true
  distDir:
    description: 'Local folder to deploy to neocities'
    default: 'public'
    required: true
  cleanup:
    description: Delete orphaned files on neocities that don't exist in distDir
    default: false
    required: true
outputs: # none
runs:
  using: 'node12'
  main: 'index.js'
