name: 'Deploy to Neocities'
description: 'Efficiently deploy a folder to Neocities.org'
branding:
  icon: aperture
  color: orange
inputs:
  api_token:  # api token for site to deploy to
    description: 'Neocities API token for site to deploy to'
    required: true
  dist_dir:
    description: 'Local folder to deploy to neocities'
    default: 'public'
    required: true
  cleanup:
    description: Delete orphaned files on neocities that don't exist in distDir
    default: false
    required: true
outputs: # none
runs:
  using: 'node12'
  main: 'dist/index.js'
